---
name: Run tests and package firmware
on:
  push:
    branches:
      - 'doom*'
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - 'companion/**'
      - '.gitpod.yml'
      - '.devcontainer/**'

jobs:
  build:
    name: Run builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - tx16s
    container:
      image: ghcr.io/edgetx/edgetx-dev:latest
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
        run: |
          echo "Running firmware build"
          ./tools/build-gh.sh

      - name: Compose release filename
        run: |
          echo "artifact_name=doom_tx16s_fw" >> $GITHUB_ENV
          wget https://wadhosting.com/Wad/Download/5B2E249B9C5133EC987B3EA77596381DC0D6BC1D/DOOM1.WAD
          mkdir -p DOOM
          mv DOOM1.WAD DOOM/

      - name: Package firmware ${{ matrix.target }}
        uses: 'actions/upload-artifact@v2'
        with:
          name: "${{ env.artifact_name }}"
          path: |
            LICENSE
            *.bin
            DOOM
            README.md
          retention-days: 15
          if-no-files-found: error
